### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by ssbilakeri** [nickhuang1996/HJL-re-id#1]
(base) D:\project_dir\HJLReID\MDRSREID>python demo.py --model_name MDRS    --exp_dir /project_dir/weights_results/HJLReID1/MDRS_ADAM_random_erasing_margin_0.3_market_best    --default_config_path /project_dir/HJLReID/MDRSREID/Settings/config/default_config.py    --ow_config_path /project_dir/HJLReID/MDRSREID/Settings/config/overwrite_config/MDRS_config_ADAM_best_market1501.txt    --ow_str cfg.dataset.train.name = 'market1501'
destination path dir /project_dir/weights_results/HJLReID1/MDRS_ADAM_random_erasing_margin_0.3_market_best has been already exist.
ow_config_path is: /project_dir/HJLReID/MDRSREID/Settings/config/overwrite_config/MDRS_config_ADAM_best_market1501.txt
ow_str is: cfg.dataset.train.name
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    cfg = pre_initialization()
  File "..\MDRSREID\Trainer\pre_initialization\__init__.py", line 11, in pre_initialization
    cfg = init_config()
  File "..\MDRSREID\Trainer\pre_initialization\init_config.py", line 35, in init_config
    overwrite_config_file(dst_config_path, ow_str=args.ow_str)
  File "..\MDRSREID\utils\config_utils\overwrite_config_file.py", line 24, in overwrite_config_file
    key, value = cfg.split('=')
ValueError: not enough values to unpack (expected 2, got 1)

Please help me to fix this error

**Comment by nickhuang1996** [comment]
> t_ma
If you use cmd, you will add double quotation mark to the expression：
--ow_str "cfg.dataset.train.name = 'market1501'"

**Comment by nickhuang1996** [comment]
@ssbilakeri 
If you use cmd or power shell, you need to add double quotation mark to the expression：
--ow_str "cfg.dataset.train.name = 'market1501'"
I recommend you to use Pycharm to build this project so that avoid this problem.

**Comment by ssbilakeri** [comment]
Hi,
when I try to train with only baseline getting below error. can you please tell me the reason for it.
I have changed ow_config_path to baseline_config.tx


Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    trainer.train()
  File "..\MDRSREID\Trainer\MDRSReIDTrainer.py", line 107, in train
    pred = self.model.forward(item, cfg=self.cfg, forward_type='Supervised')
  File "..\MDRSREID\Networks\__init__.py", line 101, in forward
    return self.model(in_dict, cfg, forward_type=forward_type)
  File "C:\Users\ssbilakeri\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "..\MDRSREID\Networks\MDRS\__init__.py", line 52, in forward
    out_dict['multi_seg_pred_list'] = self.multi_seg_forward(in_dict)
  File "..\MDRSREID\Networks\MDRS\__init__.py", line 38, in multi_seg_forward
    return self.multi_seg(in_dict)
  File "C:\Users\ssbilakeri\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "..\MDRSREID\Networks\MDRS\MDRS_multi_seg.py", line 99, in forward
    multi_seg_pred_list.append(self.conv(self.relu(self.bn(self.deconv2(self.deconv1(feat_list[i]))))))
IndexError: list index out of range
