### ISSUE TITLE
ValueError: Expected input batch_size (98304) to match target batch_size (24576).

### ISSUE THREAD

**Issue by ssbilakeri** [nickhuang1996/HJL-re-id#2]
when I use MDRS2_config file as overwrite_file getting bellow error. please suggest me where Im wrong

Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    trainer.train()
  File "..\MDRSREID\Trainer\MDRSReIDTrainer.py", line 111, in train
    source_loss += self.loss_functions[loss_type.name](item, pred, step=self.current_step)['loss']
  File "..\MDRSREID\Loss_Meter\Multi_Seg_loss.py", line 24, in __call__
    loss_list = [self.criterion(multi_seg_pred_list[i].permute(0, 2, 3, 1).contiguous().view(-1, C), ps_label) for i in range(len(multi_seg_pred_list))]
  File "..\MDRSREID\Loss_Meter\Multi_Seg_loss.py", line 24, in <listcomp>
    loss_list = [self.criterion(multi_seg_pred_list[i].permute(0, 2, 3, 1).contiguous().view(-1, C), ps_label) for i in range(len(multi_seg_pred_list))]
  File "C:\Users\ssbilakeri\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\ssbilakeri\Anaconda3\lib\site-packages\torch\nn\modules\loss.py", line 904, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "C:\Users\ssbilakeri\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1970, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "C:\Users\ssbilakeri\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1788, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (98304) to match target batch_size (24576).

**Comment by nickhuang1996** [comment]
@ssbilakeri 
For this bugs, I have rewritten the code for overwrite_configs and modified the [MDRS_seg_loss.py](./MDRSREID/Networks/MDRS/MDRS_multi_seg.py) for two options, which is correponding to backbone options.

**Comment by qianqiansbaby** [comment]
@ssbilakeri 
Hi, I have same problems but I choose use option 2 then no errors and I get the same results better than this papers. Could you please tell me how to choose these overwrite config files for training please!:relaxed:

**Comment by qianqiansbaby** [comment]
@nickhuang1996 
I have another question：
How the [RamdomIdentitySampler2.py](../tree/master/MDRSREID/DataLoaders/Sampler/RamdomIdentitySampler2.py) works?
 I can't understand how to use this sampler.:sob: Please tell me how to use it for training.

**Comment by nickhuang1996** [comment]
@qianqiansbaby 
This RamdomIdentitySampler is to select identities and their images. For example, if you set identities to 4 and their images to 8, then the batch size for training is **_4*8 = 32_**.

**Comment by ssbilakeri** [comment]
Resolved error.
Thank you.

**Comment by nickhuang1996** [comment]
@ssbilakeri 
Good luck!:relaxed: You can use my MDRS_feat_dict.mat files to test and no problem. Thank you for cooperating with me for modification on this code.:stuck_out_tongue_winking_eye:

**Comment by hhhjjjooo** [comment]
@nickhuang1996 
Thank you for resolving errors.😘 I have achieved excellent results through your feat_dict files.👍
